FROM condaforge/miniforge3:24.11.3-2

RUN apt-get update && apt-get install -y \  
    libgl1-mesa-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN conda install -y python=3.10

# Create separate conda environment for micro-sam
RUN conda install -c conda-forge micro_sam=1.4.0

RUN mkdir -p /tmp/micro-sam

CMD ["bash"]